-- ============================================================
-- DITTEAU DATA GOVERNANCE - SCHEMA SETUP
-- ============================================================
-- Purpose: Create governance database and foundational objects
-- Run As: ACCOUNTADMIN
-- Run Order: 1 (First script to run)
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- SECTION 1: CREATE GOVERNANCE DATABASE
-- ============================================================

-- Create shared governance database (used across DEV, TEST, PROD)
CREATE DATABASE IF NOT EXISTS DITTEAU_DATA_GOVERNANCE
    COMMENT = 'Shared governance database for policies, tags, masking, and row access across all environments';

-- Create governance schema
CREATE SCHEMA IF NOT EXISTS DITTEAU_DATA_GOVERNANCE.GOVERNANCE
    COMMENT = 'Data governance policies, tags, masking, row access, and helper views';

-- ============================================================
-- SECTION 2: CREATE GOVERNANCE ROLE
-- ============================================================

-- Create governance admin role
CREATE ROLE IF NOT EXISTS GOVERNANCE_ADMIN_ROLE
    COMMENT = 'Role for managing data governance policies, tags, and security';

-- Grant schema access
GRANT USAGE ON DATABASE DITTEAU_DATA_GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT ALL ON SCHEMA DITTEAU_DATA_GOVERNANCE.GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant ability to create governance objects
GRANT CREATE TAG ON SCHEMA DITTEAU_DATA_GOVERNANCE.GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT CREATE MASKING POLICY ON SCHEMA DITTEAU_DATA_GOVERNANCE.GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA DITTEAU_DATA_GOVERNANCE.GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT CREATE VIEW ON SCHEMA DITTEAU_DATA_GOVERNANCE.GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT CREATE TABLE ON SCHEMA DITTEAU_DATA_GOVERNANCE.GOVERNANCE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant ability to APPLY governance objects (critical!)
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT APPLY TAG ON ACCOUNT TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant access to account usage for monitoring
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- ============================================================
-- SECTION 3: GRANT ACCESS TO ENVIRONMENT DATABASES
-- ============================================================

-- Governance admin needs to see all schemas in all environments to apply policies
-- DEV Environment
GRANT USAGE ON DATABASE DITTEAU_DATA_DEV TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_DEV.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_DEV.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_DEV.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- TEST Environment
GRANT USAGE ON DATABASE DITTEAU_DATA_TEST TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_TEST.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_TEST.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_TEST.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- PROD Environment
GRANT USAGE ON DATABASE DITTEAU_DATA_PROD TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_PROD.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_PROD.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA_PROD.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant SELECT on all tables (needed to apply policies) - DEV
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_DEV.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_DEV.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_DEV.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant SELECT on all tables (needed to apply policies) - TEST
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_TEST.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_TEST.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_TEST.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant SELECT on all tables (needed to apply policies) - PROD
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_PROD.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_PROD.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA_PROD.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant on future tables - DEV
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_DEV.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_DEV.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_DEV.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant on future tables - TEST
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_TEST.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_TEST.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_TEST.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- Grant on future tables - PROD
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_PROD.DEPOSIT TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_PROD.DETERGE TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA_PROD.DISTRIBUTE TO ROLE GOVERNANCE_ADMIN_ROLE;

-- ============================================================
-- SECTION 4: GRANT GOVERNANCE ROLE TO USERS
-- ============================================================

-- Grant governance admin role to appropriate users
-- IMPORTANT: Replace with your actual usernames

-- Example grants (uncomment and customize):
-- GRANT ROLE GOVERNANCE_ADMIN_ROLE TO USER LVANPELT;
-- GRANT ROLE GOVERNANCE_ADMIN_ROLE TO USER DATA_GOVERNANCE_LEAD;
-- GRANT ROLE GOVERNANCE_ADMIN_ROLE TO USER SECURITY_ADMIN;

-- Grant to SYSADMIN for administrative access
GRANT ROLE GOVERNANCE_ADMIN_ROLE TO ROLE SYSADMIN;

-- ============================================================
-- SECTION 5: CREATE WAREHOUSES FOR GOVERNANCE WORK
-- ============================================================

-- Create dedicated warehouses for governance operations in each environment
CREATE WAREHOUSE IF NOT EXISTS GOVERNANCE_DEV
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'DEV warehouse for governance policy management and auditing';

CREATE WAREHOUSE IF NOT EXISTS GOVERNANCE_TEST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'TEST warehouse for governance policy management and auditing';

CREATE WAREHOUSE IF NOT EXISTS GOVERNANCE_PROD
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'PROD warehouse for governance policy management and auditing';

-- Grant warehouse usage to governance admin
GRANT USAGE ON WAREHOUSE GOVERNANCE_DEV TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE GOVERNANCE_TEST TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE GOVERNANCE_PROD TO ROLE GOVERNANCE_ADMIN_ROLE;

-- ============================================================
-- SECTION 6: VERIFICATION
-- ============================================================

-- Verify database and schema creation
SHOW SCHEMAS IN DATABASE DITTEAU_DATA_GOVERNANCE;

-- Verify role creation
SHOW ROLES LIKE 'GOVERNANCE_ADMIN_ROLE';

-- Verify grants to governance role
SHOW GRANTS TO ROLE GOVERNANCE_ADMIN_ROLE;

-- ============================================================
-- SECTION 7: NEXT STEPS
-- ============================================================

/*
SETUP COMPLETE

Next Steps:
-----------
1. Grant GOVERNANCE_ADMIN_ROLE to appropriate users (Section 4)
2. Run 01_roles_and_grants.sql to set up data layer roles
3. Run 10_tags.sql to create tag taxonomy
4. Run 11_masking_policies.sql to create masking policies
5. Run 12_row_access_policies.sql to create row access policies

Testing:
--------
-- Switch to governance role and verify access
USE ROLE GOVERNANCE_ADMIN_ROLE;
USE DATABASE DITTEAU_DATA_GOVERNANCE;
USE SCHEMA GOVERNANCE;
USE WAREHOUSE GOVERNANCE_DEV;  -- Or GOVERNANCE_TEST or GOVERNANCE_PROD

-- Should succeed
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();

-- Verify you can see environment databases
SHOW DATABASES LIKE 'DITTEAU_DATA_%';

-- Verify you can see schemas in each environment
SHOW SCHEMAS IN DATABASE DITTEAU_DATA_DEV;
SHOW TABLES IN SCHEMA DITTEAU_DATA_DEV.DEPOSIT;
SHOW TABLES IN SCHEMA DITTEAU_DATA_DEV.DETERGE;
SHOW TABLES IN SCHEMA DITTEAU_DATA_DEV.DISTRIBUTE;
*/

-- ============================================================
-- END OF SCRIPT
-- ============================================================
