-- ============================================================
-- DITTEAU DATA GOVERNANCE - ROLES AND GRANTS
-- ============================================================
-- Purpose: Create role hierarchy for data access control
-- Run As: ACCOUNTADMIN (or SECURITYADMIN)
-- Run Order: 2 (After 00_governance_schema.sql)
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- SECTION 1: CREATE DATA ACCESS ROLES
-- ============================================================

-- ───────────────────────────────────────────────────────────
-- Engineering and Development Roles
-- ───────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE
    COMMENT = 'Data engineers - can read/write all layers, see partial PII for debugging';

CREATE ROLE IF NOT EXISTS DBT_CLOUD_PROD_ROLE
    COMMENT = 'dbt Cloud production service account - full transformation access';

CREATE ROLE IF NOT EXISTS DBT_CLOUD_DEV_ROLE
    COMMENT = 'dbt Cloud development - read all, write to DEV schemas only';

-- ───────────────────────────────────────────────────────────
-- Analyst Roles (by Department)
-- ───────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS DATA_ANALYST_ROLE
    COMMENT = 'General data analysts - read access to DISTRIBUTE layer only';

CREATE ROLE IF NOT EXISTS IR_ANALYST_ROLE
    COMMENT = 'Institutional Research analysts - aggregate data access';

CREATE ROLE IF NOT EXISTS REGISTRAR_ANALYST_ROLE
    COMMENT = 'Registrar analysts - full academic data access';

CREATE ROLE IF NOT EXISTS ENROLLMENT_ANALYST_ROLE
    COMMENT = 'Enrollment/Admissions analysts - prospective student data';

CREATE ROLE IF NOT EXISTS FINANCIAL_AID_ANALYST_ROLE
    COMMENT = 'Financial Aid analysts - financial and eligibility data';

-- ───────────────────────────────────────────────────────────
-- Administrative Roles
-- ───────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS DITTEAU_DATA_ADMIN
    COMMENT = 'Ditteau Data platform administrators - full access to all';

-- ============================================================
-- SECTION 2: ROLE HIERARCHY
-- ============================================================

-- Set up role inheritance (roles granted to other roles)

-- Admin roles inherit all analyst roles
GRANT ROLE DATA_ANALYST_ROLE TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE IR_ANALYST_ROLE TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE REGISTRAR_ANALYST_ROLE TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE ENROLLMENT_ANALYST_ROLE TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE FINANCIAL_AID_ANALYST_ROLE TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE DATA_ENGINEER_ROLE TO ROLE DITTEAU_DATA_ADMIN;
GRANT ROLE GOVERNANCE_ADMIN_ROLE TO ROLE DITTEAU_DATA_ADMIN;

-- Data engineers can use analyst roles for testing
GRANT ROLE DATA_ANALYST_ROLE TO ROLE DATA_ENGINEER_ROLE;

-- Grant to SYSADMIN for administrative purposes
GRANT ROLE DITTEAU_DATA_ADMIN TO ROLE SYSADMIN;

-- ============================================================
-- SECTION 3: WAREHOUSE GRANTS
-- ============================================================

-- Create warehouses if they don't exist
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Primary warehouse for dbt transformations';

CREATE WAREHOUSE IF NOT EXISTS ANALYST_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for analyst queries';

-- Grant warehouse access
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DBT_CLOUD_DEV_ROLE;

GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE IR_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE FINANCIAL_AID_ANALYST_ROLE;

-- ============================================================
-- SECTION 4: DATABASE AND SCHEMA GRANTS
-- ============================================================

-- ───────────────────────────────────────────────────────────
-- Engineering Roles - Full Access to All Layers
-- ───────────────────────────────────────────────────────────

-- DATA_ENGINEER_ROLE
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DITTEAU_DATA TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DITTEAU_DATA.DEPOSIT TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ENGINEER_ROLE;

-- Future grants for engineers
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DEPOSIT TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ENGINEER_ROLE;

-- DBT_CLOUD_PROD_ROLE (similar to engineer but for service account)
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DITTEAU_DATA TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DEPOSIT TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON SCHEMA DITTEAU_DATA.DETERGE TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DBT_CLOUD_PROD_ROLE;

-- Future grants for dbt prod
GRANT ALL ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE DBT_CLOUD_PROD_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DBT_CLOUD_PROD_ROLE;

-- ───────────────────────────────────────────────────────────
-- Analyst Roles - Read-Only Access to DISTRIBUTE Layer
-- ───────────────────────────────────────────────────────────

-- Grant to all analyst roles
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE IR_ANALYST_ROLE;
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT USAGE ON DATABASE DITTEAU_DATA TO ROLE FINANCIAL_AID_ANALYST_ROLE;

GRANT USAGE ON SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE IR_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE FINANCIAL_AID_ANALYST_ROLE;

-- Grant SELECT on all tables and views in DISTRIBUTE
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE FINANCIAL_AID_ANALYST_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE FINANCIAL_AID_ANALYST_ROLE;

-- Future grants for analysts
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE FINANCIAL_AID_ANALYST_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE REGISTRAR_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE ENROLLMENT_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DISTRIBUTE TO ROLE FINANCIAL_AID_ANALYST_ROLE;

-- ───────────────────────────────────────────────────────────
-- IR Analysts - Also Need DETERGE Access for Custom Analysis
-- ───────────────────────────────────────────────────────────

GRANT USAGE ON SCHEMA DITTEAU_DATA.DETERGE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE IR_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DITTEAU_DATA.DETERGE TO ROLE IR_ANALYST_ROLE;

-- ============================================================
-- SECTION 5: GRANT ROLES TO USERS
-- ============================================================

-- IMPORTANT: Customize these grants for the institution
-- Replace with their actual usernames and email addresses

/*
-- Example user grants (uncomment and customize):

-- Data Engineers
GRANT ROLE DATA_ENGINEER_ROLE TO USER LVANPELT;
GRANT ROLE DATA_ENGINEER_ROLE TO USER JOHN_DOE;

-- Institutional Research
GRANT ROLE IR_ANALYST_ROLE TO USER IR_DIRECTOR;
GRANT ROLE IR_ANALYST_ROLE TO USER IR_ANALYST_1;

-- Registrar
GRANT ROLE REGISTRAR_ANALYST_ROLE TO USER REGISTRAR;
GRANT ROLE REGISTRAR_ANALYST_ROLE TO USER REGISTRAR_STAFF;

-- Enrollment
GRANT ROLE ENROLLMENT_ANALYST_ROLE TO USER ENROLLMENT_DIR;
GRANT ROLE ENROLLMENT_ANALYST_ROLE TO USER ADMISSIONS_ANALYST;

-- Financial Aid
GRANT ROLE FINANCIAL_AID_ANALYST_ROLE TO USER FA_DIRECTOR;
GRANT ROLE FINANCIAL_AID_ANALYST_ROLE TO USER FA_COUNSELOR;

-- General Analysts
GRANT ROLE DATA_ANALYST_ROLE TO USER ANALYST_1;
GRANT ROLE DATA_ANALYST_ROLE TO USER ANALYST_2;

-- Admins
GRANT ROLE DITTEAU_DATA_ADMIN TO USER LVANPELT;
GRANT ROLE GOVERNANCE_ADMIN_ROLE TO USER DATA_GOVERNANCE_LEAD;
*/

-- ============================================================
-- SECTION 6: VERIFICATION
-- ============================================================

-- Show all roles
SHOW ROLES LIKE '%ANALYST%';
SHOW ROLES LIKE '%ENGINEER%';
SHOW ROLES LIKE '%DBT%';
SHOW ROLES LIKE '%ADMIN%';

-- Verify role hierarchy
SHOW GRANTS TO ROLE DITTEAU_DATA_ADMIN;
SHOW GRANTS TO ROLE DATA_ENGINEER_ROLE;
SHOW GRANTS TO ROLE IR_ANALYST_ROLE;

-- Verify warehouse access
SHOW GRANTS ON WAREHOUSE TRANSFORM_WH;
SHOW GRANTS ON WAREHOUSE ANALYST_WH;

-- Verify database access
SHOW GRANTS ON DATABASE DITTEAU_DATA;
SHOW GRANTS ON SCHEMA DITTEAU_DATA.DISTRIBUTE;

-- ============================================================
-- SECTION 7: NEXT STEPS
-- ============================================================

/*
ROLES AND GRANTS SETUP COMPLETE

Next Steps:
-----------
1. Grant roles to actual users (Section 5)
2. Test access by switching roles
3. Run 10_tags.sql to create tag taxonomy
4. Run masking and row access policies
5. Test that masking works correctly per role

Testing Each Role:
------------------

-- Test as Data Engineer
USE ROLE DATA_ENGINEER_ROLE;
USE WAREHOUSE TRANSFORM_WH;
SELECT CURRENT_ROLE();
SHOW TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE;

-- Test as IR Analyst
USE ROLE IR_ANALYST_ROLE;
USE WAREHOUSE ANALYST_WH;
SELECT CURRENT_ROLE();
SHOW TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE;

-- Test as Registrar Analyst
USE ROLE REGISTRAR_ANALYST_ROLE;
USE WAREHOUSE ANALYST_WH;
SELECT CURRENT_ROLE();
SHOW TABLES IN SCHEMA DITTEAU_DATA.DISTRIBUTE;

Role Access Summary:
-------------------
DATA_ENGINEER_ROLE: Read/Write all layers, partial PII visibility
DBT_CLOUD_PROD_ROLE: Read DEPOSIT, Write DETERGE/DISTRIBUTE
IR_ANALYST_ROLE: Read DETERGE/DISTRIBUTE, aggregate data only
REGISTRAR_ANALYST_ROLE: Read DISTRIBUTE, full academic data
ENROLLMENT_ANALYST_ROLE: Read DISTRIBUTE, prospective students
FINANCIAL_AID_ANALYST_ROLE: Read DISTRIBUTE, financial data
DATA_ANALYST_ROLE: Read DISTRIBUTE only
*/

-- ============================================================
-- END OF SCRIPT
-- ============================================================

